### ISSUE TITLE
Including Freehaven Bibtex library on Anonymity

### ISSUE THREAD

**Issue by azet** [Daeinar/crypto-bib#1]
Hi,

What do you think about mirroring the Freehaven Library inside this project (maybe scripted + cron)? Most of these papers have either a direct connection to cryptography (i.e. are crypto papers) or are related to matters that are philosophically aligned with the topics of cryptography research (anonymity, privacy, anonymous-payment systems et cetera): http://freehaven.net/anonbib/

Bibtex sources for all selected papers of the freehaven library are available at this location: http://freehaven.net/anonbib/bibtex.html

**Comment by Daeinar** [comment]
Hi,

thanks for your input but this repository is not really maintained any longer. The CryptoBib authors (@fabrice102 and @michelabdalla) maintain their own Github repo now, see: https://github.com/cryptobib 

Maybe they are willing to include it there?

**Comment by azet** [comment]
Ah, damn. I thought something is amiss here. Thanks for the pointer will ask them over there.
